<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <RootNamespace>SAIN</RootNamespace>
    <AssemblyName>SAIN</AssemblyName>
    <SptInstallDir Condition="'$(SptInstallDir)' == '' and '$(SPT_INSTALL_DIR)' != ''">$(SPT_INSTALL_DIR)</SptInstallDir>
    <SptInstallDir Condition="'$(SptInstallDir)' == ''">$(MSBuildProjectDirectory)\..\..</SptInstallDir>
    <EftManagedDir>$(SptInstallDir)\EscapeFromTarkov_Data\Managed</EftManagedDir>
    <BepInExPluginDir>$(SptInstallDir)\BepInEx\plugins</BepInExPluginDir>
  </PropertyGroup>

  <!-- targets -->
  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <None Include="References\**" />
    <None Include="ServerMod\**" />
    <Compile Remove="ServerModNet\**" />
    <EmbeddedResource Remove="ServerModNet\**" />
    <None Remove="ServerModNet\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.43" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(EftManagedDir)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="bsg.console.core">
      <HintPath>$(EftManagedDir)\bsg.console.core.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(EftManagedDir)\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Comfort.Unity">
      <HintPath>$(EftManagedDir)\Comfort.Unity.dll</HintPath>
    </Reference>
    <Reference Include="CommonExtensions" HintPath="References\CommonExtensions.dll" Private="false" />
    <Reference Include="DissonanceVoip" HintPath="References\DissonanceVoip.dll" Private="false" />
    <Reference Include="DrakiaXYZ-BigBrain">
      <HintPath>$(BepInExPluginDir)\DrakiaXYZ-BigBrain.dll</HintPath>
    </Reference>
    <Reference Include="ItemComponent.Types" HintPath="References\ItemComponent.Types.dll" Private="false" />
    <Reference Include="Newtonsoft.Json" HintPath="References\Newtonsoft.Json.dll" Private="false" />
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(EftManagedDir)\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>$(BepInExPluginDir)\spt\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-core">
      <HintPath>$(BepInExPluginDir)\spt\spt-core.dll</HintPath>
    </Reference>
    <Reference Include="spt-custom">
      <HintPath>$(BepInExPluginDir)\spt\spt-custom.dll</HintPath>
    </Reference>
    <Reference Include="spt-debugging">
      <HintPath>$(BepInExPluginDir)\spt\spt-debugging.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>$(BepInExPluginDir)\spt\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="spt-singleplayer">
      <HintPath>$(BepInExPluginDir)\spt\spt-singleplayer.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>$(EftManagedDir)\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(EftManagedDir)\UnityEngine.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <MakeDir Directories="$(BepInExPluginDir)\SAIN" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BepInExPluginDir)\SAIN" />
  </Target>

</Project>
