<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SAIN</AssemblyName>
    <RootNamespace>SAIN.Server</RootNamespace>
    <Version>2.3.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <SptRoot Condition="'$(SptRoot)' == ''">D:\SPT\SPT_Runtime</SptRoot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SPTarkov.Common">
      <HintPath>$(SptRoot)\SPTarkov.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>$(SptRoot)\SPTarkov.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>$(SptRoot)\SPTarkov.Server.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>$(SptRoot)\SemanticVersioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
